version: '3'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=diligentroot
      - MYSQL_USER=alok
      - MYSQL_PASSWORD=diligentuser
      - MYSQL_DATABASE=diligentdb

  # Nee to build the web image once product is ready
  # web:
  #   build: .
  #   ports:
  #     - 8080:8080
